"""initial schema

Revision ID: ebdc40be31cf
Revises: 
Create Date: 2026-04-14 23:40:33.306691

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'ebdc40be31cf'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('data_sources',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('slug', sa.String(length=63), nullable=False),
    sa.Column('name', sa.String(length=127), nullable=False),
    sa.Column('source_type', sa.String(length=31), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('slug')
    )
    op.create_table('exercises',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('slug', sa.String(length=63), nullable=False),
    sa.Column('name', sa.String(length=127), nullable=False),
    sa.Column('category', sa.String(length=31), nullable=False),
    sa.Column('muscle_group', sa.String(length=63), nullable=True),
    sa.Column('equipment', sa.String(length=63), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('slug')
    )
    op.create_table('medication_definitions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('active_ingredient', sa.String(length=255), nullable=True),
    sa.Column('dosage_form', sa.String(length=63), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('metric_types',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('slug', sa.String(length=63), nullable=False),
    sa.Column('name', sa.String(length=127), nullable=False),
    sa.Column('category', sa.String(length=63), nullable=False),
    sa.Column('default_unit', sa.String(length=31), nullable=False),
    sa.Column('value_precision', sa.SmallInteger(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('slug')
    )
    op.create_table('symptoms',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('slug', sa.String(length=63), nullable=False),
    sa.Column('name', sa.String(length=127), nullable=False),
    sa.Column('category', sa.String(length=63), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('slug')
    )
    op.create_table('users',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('timezone', sa.String(length=63), server_default='UTC', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('daily_checkpoints',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('checkpoint_type', sa.String(length=15), nullable=False),
    sa.Column('checkpoint_date', sa.Date(), nullable=False),
    sa.Column('checkpoint_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('mood', sa.SmallInteger(), nullable=True),
    sa.Column('energy', sa.SmallInteger(), nullable=True),
    sa.Column('sleep_quality', sa.SmallInteger(), nullable=True),
    sa.Column('body_state_score', sa.SmallInteger(), nullable=True),
    sa.Column('notes', sa.String(), nullable=True),
    sa.Column('recorded_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('ingested_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('context', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.CheckConstraint('body_state_score >= 1 AND body_state_score <= 10', name='ck_daily_checkpoints_body_state_score'),
    sa.CheckConstraint('energy >= 1 AND energy <= 10', name='ck_daily_checkpoints_energy'),
    sa.CheckConstraint('mood >= 1 AND mood <= 10', name='ck_daily_checkpoints_mood'),
    sa.CheckConstraint('sleep_quality >= 1 AND sleep_quality <= 10', name='ck_daily_checkpoints_sleep_quality'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'checkpoint_type', 'checkpoint_date', name='uq_daily_checkpoint_user_type_date')
    )
    op.create_index('ix_daily_checkpoints_user_date', 'daily_checkpoints', ['user_id', 'checkpoint_date'], unique=False)
    op.create_table('medication_regimens',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('medication_id', sa.Integer(), nullable=False),
    sa.Column('dosage_amount', sa.Numeric(precision=7, scale=2), nullable=False),
    sa.Column('dosage_unit', sa.String(length=31), nullable=False),
    sa.Column('frequency', sa.String(length=31), nullable=False),
    sa.Column('instructions', sa.String(), nullable=True),
    sa.Column('prescribed_by', sa.String(length=255), nullable=True),
    sa.Column('started_at', sa.Date(), nullable=False),
    sa.Column('ended_at', sa.Date(), nullable=True),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['medication_id'], ['medication_definitions.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_medication_regimens_user_active', 'medication_regimens', ['user_id', 'is_active'], unique=False)
    op.create_table('raw_payloads',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('source_id', sa.Integer(), nullable=False),
    sa.Column('external_id', sa.String(length=255), nullable=True),
    sa.Column('payload_type', sa.String(length=63), nullable=False),
    sa.Column('payload_json', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('ingested_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('processing_status', sa.String(length=31), server_default='pending', nullable=False),
    sa.Column('processed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('error_message', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['source_id'], ['data_sources.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_raw_payloads_pending', 'raw_payloads', ['processing_status'], unique=False, postgresql_where=sa.text("processing_status = 'pending'"))
    op.create_index('ix_raw_payloads_source_external', 'raw_payloads', ['source_id', 'external_id'], unique=True, postgresql_where=sa.text('external_id IS NOT NULL'))
    op.create_index('ix_raw_payloads_user_ingested', 'raw_payloads', ['user_id', 'ingested_at'], unique=False)
    op.create_table('symptom_logs',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('symptom_id', sa.Integer(), nullable=False),
    sa.Column('intensity', sa.SmallInteger(), nullable=False),
    sa.Column('status', sa.String(length=15), server_default='active', nullable=False),
    sa.Column('trigger', sa.String(length=255), nullable=True),
    sa.Column('functional_impact', sa.String(length=15), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('ended_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('notes', sa.String(), nullable=True),
    sa.Column('recorded_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('ingested_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('context', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.CheckConstraint('intensity >= 1 AND intensity <= 10', name='ck_symptom_logs_intensity'),
    sa.ForeignKeyConstraint(['symptom_id'], ['symptoms.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_symptom_logs_user_started', 'symptom_logs', ['user_id', 'started_at'], unique=False)
    op.create_table('measurements',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('metric_type_id', sa.Integer(), nullable=False),
    sa.Column('source_id', sa.Integer(), nullable=False),
    sa.Column('value_num', sa.Numeric(), nullable=False),
    sa.Column('unit', sa.String(length=31), nullable=False),
    sa.Column('measured_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('ended_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('recorded_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('ingested_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('aggregation_level', sa.String(length=15), server_default='spot', nullable=False),
    sa.Column('is_derived', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('confidence', sa.Numeric(precision=3, scale=2), nullable=True),
    sa.Column('context', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('raw_payload_id', sa.Uuid(), nullable=True),
    sa.ForeignKeyConstraint(['metric_type_id'], ['metric_types.id'], ),
    sa.ForeignKeyConstraint(['raw_payload_id'], ['raw_payloads.id'], ),
    sa.ForeignKeyConstraint(['source_id'], ['data_sources.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_measurements_raw_payload', 'measurements', ['raw_payload_id'], unique=False)
    op.create_index('ix_measurements_user_measured', 'measurements', ['user_id', 'measured_at'], unique=False)
    op.create_index('ix_measurements_user_metric_measured', 'measurements', ['user_id', 'metric_type_id', 'measured_at'], unique=False)
    op.create_table('medication_logs',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('regimen_id', sa.Uuid(), nullable=False),
    sa.Column('status', sa.String(length=15), nullable=False),
    sa.Column('scheduled_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('taken_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('dosage_amount', sa.Numeric(precision=7, scale=2), nullable=True),
    sa.Column('dosage_unit', sa.String(length=31), nullable=True),
    sa.Column('notes', sa.String(), nullable=True),
    sa.Column('recorded_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('ingested_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['regimen_id'], ['medication_regimens.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_medication_logs_regimen', 'medication_logs', ['regimen_id'], unique=False)
    op.create_index('ix_medication_logs_user_scheduled', 'medication_logs', ['user_id', 'scheduled_at'], unique=False)
    op.create_table('workout_sessions',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('source_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=True),
    sa.Column('workout_type', sa.String(length=31), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('ended_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('duration_seconds', sa.Integer(), nullable=True),
    sa.Column('perceived_effort', sa.SmallInteger(), nullable=True),
    sa.Column('notes', sa.String(), nullable=True),
    sa.Column('recorded_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('ingested_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('raw_payload_id', sa.Uuid(), nullable=True),
    sa.Column('context', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.CheckConstraint('perceived_effort >= 1 AND perceived_effort <= 10', name='ck_workout_sessions_perceived_effort'),
    sa.ForeignKeyConstraint(['raw_payload_id'], ['raw_payloads.id'], ),
    sa.ForeignKeyConstraint(['source_id'], ['data_sources.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_workout_sessions_user_started', 'workout_sessions', ['user_id', 'started_at'], unique=False)
    op.create_table('workout_sets',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('workout_session_id', sa.Uuid(), nullable=False),
    sa.Column('exercise_id', sa.Integer(), nullable=False),
    sa.Column('set_number', sa.SmallInteger(), nullable=False),
    sa.Column('reps', sa.SmallInteger(), nullable=True),
    sa.Column('weight_kg', sa.Numeric(precision=7, scale=2), nullable=True),
    sa.Column('duration_seconds', sa.Integer(), nullable=True),
    sa.Column('distance_meters', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('rest_seconds', sa.SmallInteger(), nullable=True),
    sa.Column('notes', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['exercise_id'], ['exercises.id'], ),
    sa.ForeignKeyConstraint(['workout_session_id'], ['workout_sessions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_workout_sets_session', 'workout_sets', ['workout_session_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_workout_sets_session', table_name='workout_sets')
    op.drop_table('workout_sets')
    op.drop_index('ix_workout_sessions_user_started', table_name='workout_sessions')
    op.drop_table('workout_sessions')
    op.drop_index('ix_medication_logs_user_scheduled', table_name='medication_logs')
    op.drop_index('ix_medication_logs_regimen', table_name='medication_logs')
    op.drop_table('medication_logs')
    op.drop_index('ix_measurements_user_metric_measured', table_name='measurements')
    op.drop_index('ix_measurements_user_measured', table_name='measurements')
    op.drop_index('ix_measurements_raw_payload', table_name='measurements')
    op.drop_table('measurements')
    op.drop_index('ix_symptom_logs_user_started', table_name='symptom_logs')
    op.drop_table('symptom_logs')
    op.drop_index('ix_raw_payloads_user_ingested', table_name='raw_payloads')
    op.drop_index('ix_raw_payloads_source_external', table_name='raw_payloads', postgresql_where=sa.text('external_id IS NOT NULL'))
    op.drop_index('ix_raw_payloads_pending', table_name='raw_payloads', postgresql_where=sa.text("processing_status = 'pending'"))
    op.drop_table('raw_payloads')
    op.drop_index('ix_medication_regimens_user_active', table_name='medication_regimens')
    op.drop_table('medication_regimens')
    op.drop_index('ix_daily_checkpoints_user_date', table_name='daily_checkpoints')
    op.drop_table('daily_checkpoints')
    op.drop_table('users')
    op.drop_table('symptoms')
    op.drop_table('metric_types')
    op.drop_table('medication_definitions')
    op.drop_table('exercises')
    op.drop_table('data_sources')
    # ### end Alembic commands ###
